apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oraclecmps.sample.database.oracle
spec:
  group: sample.database.oracle
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                pdbaas_zone:
                  type: string
                pdbaas_template:
                  type: string
                pdbaas_workload:
                  type: string
                pdbaas_service:
                  type: string
                pdbaas_tbs:
                  type: string
                department:
                  type: string
                comment:
                  type: string
            status:
              type: object
              properties:
                targetUri:
                  type: string
                dbStatus:
                  type: string
      subresources:
        status: { }
  scope: Namespaced
  names:
    plural: oraclecmps
    singular: oraclecmp
    kind: OracleCMP
    shortNames:
      - pdb
